name: Buildozer Appclean

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose another runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose your Python version

    - name: Install Buildozer
      run: pip install buildozer

    - name: Run buildozer appclean
      run: buildozer appclean
